"""
Configuration file for constants
"""

CAMERA_INDEX: int = 0
FRAME_WIDTH: int = 640
FRAME_HEIGHT: int = 480

DEFAULT_MODEL_NAME: str = "yolov8n.pt"
DEFAULT_CONFIDENCE_THRESHOLD: float = 0.35
DEFAULT_IOU_THRESHOLD: float = 0.45
DEFAULT_TRACKER: str = "bytetrack.yaml"
DEFAULT_MAX_DETECTIONS: int = 100

DEFAULT_CONFIDENCE_OCR_THRESHOLD: float = 0.25